blank_issues_enabled: false
contact_links:
  - name: Email Support
    url: mailto:hlexhelftd@gmail.com
    about: Please email us if you have any questions or need direct support.
  - name: Follow on Twitter
    url: https://twitter.com/HlexNC
    about: Follow for updates and reach out for quick questions.
